[build]
  command = "npm ci && npm run prisma:generate && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-optional"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    skipBuildCache = true 